data:
  rawkitti:
    # n_pillars_x (int): The number of pillars in the x dimension of the voxel grid.
    n_pillars_x: 640
    # n_pillars_y (int): The number of pillars in the y dimension of the voxel grid.
    n_pillars_y: 640
    # point_features (int): The number of features in each point of the input point clouds.
    point_features: 3 # max 4
    x_min: -35
    x_max: 35
    y_min: -35
    y_max: 35
    z_min: -1.3 # 0.3 for waymo | -1.45 for raw kitti
    z_max: 10
    batch_size: 1
    has_test: False
    num_workers: 4
    n_points: 8192
    apply_pillarization: True
    shuffle_train: True